// CSS classes
const MAIN_TYPE = "main";
const THUMBNAIL_TYPE = "thumbnail";
const ANIMATED_SLIDES = "animated";
const SELECTED_SLIDE = "selected";
const LEFT_BUTTON = "left";
const RIGHT_BUTTON = "right";

// ...
const JUMP_THRESHOLD = 75;
const DRAG_THRESHOLD = 25;
const TRANSITION_DURATION = 200

export {
  MAIN_TYPE,
  THUMBNAIL_TYPE,
  ANIMATED_SLIDES,
  SELECTED_SLIDE,
  LEFT_BUTTON,
  RIGHT_BUTTON,
  JUMP_THRESHOLD,
  DRAG_THRESHOLD,
  TRANSITION_DURATION
};
